name: doll
favicon: null
layout_spectrum: 0.467888786457479
typography_spectrum: 0.7926777370739728
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4719404096249491
  lightness: 0.9639463506173342
  saturation: 0.2708203122019768
  rhythmicContrast: 0.8345108644571155
purpose: []
